core/app_site/urls.py
from django.contrib.sitemaps.views import sitemap
from django.urls import path

from .sitemap import StaticViewSitemap
from .views import *

sitemaps = {
    'static': StaticViewSitemap,
}
app_name = 'app_site'
handler404 = 'app_site.views.my_page_not_found'
handler500 = 'app_site.views.my_server_error'
urlpatterns = [
    path('', index, name='index'),
    path('contact', contact, name='contact'),
    path('candidate', candidate, name='candidate'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
]

core/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


from django.urls import path, include

urlpatterns = [
    path('btl-admin/', admin.site.urls),
    path('', include(('app_site.urls', 'app_site'), namespace='app_site')),
    path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/app_site/models.py
from django.db import models

# class Service(models.Model):
#     title = models.CharField(max_length=200, verbose_name='название')
#     slug = models.SlugField()
#     description = models.TextField(verbose_name='описание')
#     location = models.ManyToManyField('Location', related_name='services')
#     advantages = models.ManyToManyField('Advantage', related_name='services')
#     conditions = models.ManyToManyField('Condition', related_name='services')
#     price = models.ManyToManyField('Price', related_name='services')
#     objects = models.Manager()
#
#     def __str__(self):
#         return self.title
#
#
# class Location(models.Model):
#     title = models.CharField(max_length=200, verbose_name='место проведения')
#     objects = models.Manager()
#
#     def __str__(self):
#         return self.title
#
#
# class Advantage(models.Model):
#     title = models.CharField(max_length=200, verbose_name='преимущества')
#     description = models.TextField(verbose_name='описание')
#     objects = models.Manager()
#
#     def __str__(self):
#         return self.title
#
#
# class Condition(models.Model):
#     title = models.CharField(max_length=200, verbose_name='условия')
#     objects = models.Manager()
#
#     def __str__(self):
#         return self.title
#
#
# class Price(models.Model):
#     title = models.CharField(max_length=200, verbose_name='название тарифа')
#     price = models.DecimalField(max_length=9, )
#     service = models.ManyToManyField('Feature')
#     objects = models.Manager()
#
#     def __str__(self):
#         return self.title
#

core/app_site/views.py

import json
import sys
import datetime
import locale
import os
import time
# locale.setlocale(locale.LC_TIME, 'ru_RU')

from django.conf import settings
from django.core.cache import cache
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django import forms
from .task import send_order_to_telegram_chat, send_order_to_telegram_chat_sync

FILE_JSON_PATH = os.path.join(settings.BASE_DIR, "info")

CITY = "cities.json"
REGION = "cities_by_region.json"
MEGAPOLIS = "big_cities.json"
KAZAKHSTAN =  "kz_cities.json"

city_path = os.path.join(FILE_JSON_PATH,CITY)
region_path = os.path.join(FILE_JSON_PATH, REGION)
megapolis_path = os.path.join(FILE_JSON_PATH,MEGAPOLIS)
kazakhstan_path = os.path.join(FILE_JSON_PATH,KAZAKHSTAN)

class ContactForm(forms.Form):
    name_c = forms.CharField(max_length=50)
    telephone_c = forms.CharField(max_length=50)
    # email_c = forms.EmailField(max_length=150)
    # subject_c = forms.CharField(max_length=50)
    comments_c = forms.CharField(
        widget=forms.Textarea, max_length=2000, required=False)


class HeadHunterForm(forms.Form):
    name = forms.CharField(max_length=50)
    telephone = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=150)
    position = forms.CharField(max_length=50)
    city = forms.CharField(max_length=50)
    country = forms.CharField(max_length=50)
    age = forms.CharField(max_length=50, required=False)
    sex = forms.CharField(max_length=50, required=False)
    height = forms.CharField(max_length=50, required=False)
    weight = forms.CharField(max_length=50, required=False)
    clothes_size = forms.CharField(max_length=50, required=False)
    shoes_size = forms.CharField(max_length=50, required=False)
    experience = forms.CharField(
        widget=forms.Textarea, max_length=2000, required=False)
    preferences = forms.CharField(
        widget=forms.Textarea, max_length=2000, required=False)


def index(request):
    time_cache = 604800

    cities = cache.get('all_cities')
    if not cities:
        with open(city_path, 'r', encoding='utf-8') as json_file:
            data = json.load(json_file)
        cities = cache.set('all_cities', data, time_cache)

    region_city = cache.get('region_city')
    if not region_city:
        with open(region_path, 'r', encoding='utf-8') as json_file:
            data = json.load(json_file)
        region_city = cache.set('region_city', data, time_cache)

    big_cities = cache.get('big_cities')
    if not big_cities:
        with open(megapolis_path, 'r', encoding='utf-8') as json_file:
            data = json.load(json_file)
        big_cities = cache.set('big_cities', data, time_cache)

    kz_cities = cache.get('kz_cities')
    if not kz_cities:
        with open(kazakhstan_path, 'r', encoding='utf-8') as json_file:
            data = json.load(json_file)
        kz_cities = cache.set('kz_cities', data, time_cache)

    context = {
        'cities': cities,
        'big_cities': big_cities,
        'kz_cities': kz_cities,
        'form': ContactForm(),
        'region_city': region_city,
    }
    return render(request, 'index.html', context=context)


def contact(request):
    if request.method == 'POST' and request.is_ajax():
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = 'ЗАКАЗЧИК: ' # + form.cleaned_data['subject_c']
            body = {
                'name': form.cleaned_data['name_c'],
                # 'email': form.cleaned_data['email_c'],
                'telephone': form.cleaned_data['telephone_c'],
                # 'subject': form.cleaned_data['subject_c'],
                'comments': form.cleaned_data['comments_c'],
            }
            message = "\n".join(body.values())
            # try:
            finale_message = "🔥 Заказ\n🕑 {date}\n👥 {name}\n☎ {phone}\n✍ сообщение:{msg} ".format(
                # order_id=filename,
                date=datetime.datetime.now().strftime(" %d-%b-%y (%H:%M)"),
                name=body.get('name', 'anon'),
                #email= "", # body.get('email', 'anon'),
                phone=body.get('telephone', 'anon'),
                #subject="", # body.get('subject', 'anon'),
                msg=body.get('comments', 'нет комментария')
)           # sync version
            send_order_to_telegram_chat_sync(finale_message)
            # async version
            time.sleep(1)
            # send_order_to_telegram_chat.apply_async(
            #     kwargs={'data': finale_message},
            #     expires=float(1)
            #     )

            # send_mail(
            #     subject=subject,
            #     message=message,
            #     from_email=settings.EMAIL_HOST_USER,
            #     recipient_list=[settings.EMAIL_HOST_USER,]
            # )
            response = {'message': True}
                # response = {'message': False, "error": e}
            # except Exception as e:
            #     response = {'message': False, "error": e}
            #     # return HttpResponse('Найден некорректный заголовок')
            return JsonResponse(response)

    response = {'message': False}
    return JsonResponse(response)


def candidate(request):
    if request.method == 'POST' and request.is_ajax():
        form = HeadHunterForm(request.POST)
        if form.is_valid():
            subject = 'СОИСКАТЕЛЬ: ' + form.cleaned_data['position'] + ' (' + form.cleaned_data['city'] + ")"
            body = {
                'name': 'имя: ' + form.cleaned_data['name'],
                'email': 'почта: ' + form.cleaned_data['email'],
                'position': 'вакансия: ' + form.cleaned_data['position'],
                'telephone': 'телефон: ' + form.cleaned_data['telephone'],
                'country': 'страна: ' + form.cleaned_data['country'],
                'city': 'город: ' + form.cleaned_data['city'],
            }
            if form.cleaned_data.get('age'):
                age = {'age':  form.cleaned_data.get('age')} #'полных лет: ' + form.cleaned_data.get('age')}
                body.update(age)
            if form.cleaned_data.get('sex'):
                sex = {'sex': form.cleaned_data.get('sex')} #'пол: ' + form.cleaned_data.get('sex')}
                body.update(sex)
            if form.cleaned_data.get('height'):
                height = {'height': form.cleaned_data.get('height')} # 'рост: ' + form.cleaned_data.get('height')}
                body.update(height)
            if form.cleaned_data.get('weight '):
                weight = {'weight': form.cleaned_data.get('weight')} #'вес:' + form.cleaned_data.get('weight')}
                body.update(weight)
            if form.cleaned_data.get('clothes_size'):
                clothes_size = {'clothes_size': form.cleaned_data.get('clothes_size')} #'размер одежды: ' + form.cleaned_data.get('clothes_size')}
                body.update(clothes_size)
            if form.cleaned_data.get('shoes_size'):
                shoes_size = {'shoes_size': form.cleaned_data.get('shoes_size')} # 'размер обуви: ' + form.cleaned_data.get('shoes_size')}
                body.update(shoes_size)
            if form.cleaned_data.get('experience'):
                experience = {'experience': form.cleaned_data.get('experience')} #'опыт работы: ' + form.cleaned_data.get('experience')}
                body.update(experience)
            if form.cleaned_data.get('preferences'):
                preferences = {'preferences': form.cleaned_data.get('preferences')} #'пожелания: ' + form.cleaned_data.get('preferences')}
                body.update(preferences)
            message = "\n".join(body.values())


            try:
                finale_message = "✅ Вакансия\n🕑 {date}\n👥 {name}\n✉ {email}\n☎ {phone}\n★ {position}\n\n⛳ {city}\n⛳{country}\n\n⚪ возраст: {age}\n⚪ пол: {sex}\n⚪ рост: {height}\n⚪ все: {weight}\n⚪ размер одежды: {clothes_size}\n⚪ размер обуви: {shoes_size}\n\n⏳ опыт:{experience}\n💰 пожелания:{preferences}\n\n\n#{vac}\n#{place}".format(# order_id=filename,
                date=datetime.datetime.now().strftime("%d-%b-%y (%H:%M)"),
                name=body.get('name', 'не указан'),
                email=body.get('email','не указан'),
                phone=body.get('telephone', 'не указан'),
                position=body.get('position', 'не указан'),

                country = body.get('country', 'anon'),
                city = body.get('city', 'anon'),
                age = body.get('age', 'не указан'),
                sex = body.get('sex', 'не указан'),
                height = body.get('height', 'не указан'),
                weight = body.get('weight', 'не указан'),
                clothes_size = body.get('clothes_size', 'не указан'),
                shoes_size = body.get('shoes_size', 'не указан'),
                experience = body.get('experience', 'не указан'),
                preferences = body.get('preferences', 'не указан'),
                vac = body.get('position', 'anon').split(":")[1].replace('-', '_').strip(),
                place = body.get('city', 'anon').split(":")[1].strip()

    )
                send_order_to_telegram_chat.apply_async(
                    kwargs={'data': finale_message}, 
                    expires=float(1)
                    )
                # send_mail(
                #     subject=subject,
                #     message=message,
                #     from_email=settings.EMAIL_HOST_USER,
                #     recipient_list=[settings.EMAIL_HOST_USER]
                # )
                response = {'message': True}
            except BadHeaderError:
                return HttpResponse('Найден некорректный заголовок')
            return JsonResponse(response)


core/app_site/templates/about_me.html
  <!-- Start -->
        <section class="section mt-5 bg-dark" id="about">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-5 col-md-6">
                        <img src="/assets/images/about.jpg" class="rounded shadow img-fluid" alt="">
                    </div><!--end col-->

                    <div class="col-lg-7 col-md-6 mt-4 mt-sm-0 pt-2 pt-sm-0">
                        <div class="ms-lg-5">
                            <div class="section-title">
                                <h4 class="title mb-3 text-light" >Дарья Азарова</h4>
                                <p class="text-muted">Основатель и руководитель международного маркетингового агентства полного цикла BTL+, которое специализируется на всех видах рекламы.</p>
                                <p class="text-muted mb-0">Более 22 лет опыта работы в рекламе и маркетинге, 15 из них — на руководящей должности. На протяжении 18 лет занимается предпринимательской деятельностью в различных нишах: производство, аренда недвижимости, сфера услуг, организация рекламных проектов в различных городах и странах.</p>
                            </div>
                            <div class="mt-4 pt-2">
                                 <p class="text-muted">Участник конкурса <a href="https://xn--80aebkafpsudb6lvah.xn--p1ai/azarova"><b>"ГЛАВНЫЕ ЖЕНЩИНЫ - 2024"</b></a> в номинации: <b>КОНСАЛТИНГ И ЮРИДИЧЕСКИЕ УСЛУГИ</b></p>
                                <a href="https://xn--80aebkafpsudb6lvah.xn--p1ai/azarova" target="_blank" class="btn btn-warning">Главные женщины.рф</a>
                            </div>
                        </div>
                    </div><!--end col-->
                </div><!--end row-->
            </div><!--end container-->
        </section><!--end section-->

core/app_site/templates/banner.html
{% load static %}
<section  class="swiper-slider-hero position-relative d-block vh-100" id="home">
     <!-- style="background: url(/static/images/spinner.gif) center center no-repeat"> -->
    <div class="swiper-container"  >
        <div class="swiper-wrapper" >
            <div class="swiper-slide container__size overflow-hidden">
                <div class="slide-inner slide-bg-image container__size"
                     data-background="{% static 'images/carousel/animated.gif' %}">
                    <div class="bg-overlay"></div>
                    <div class="container p-2 mt-5">
                        <div class="row justify-content-around">
                               <div class="col-12" >
                                <div class="title-heading text-start banner-title">
                                    <h1 class="title__size text-start text-white text-uppercase title-dark fw-bold">
                                        Рекламное агентство BTL+
                                    </h1>
                                    <p class="subtitle__size ">Организация и проведение промо-акций в городах  <br>России и Казахстана
                                    </p>
                                    <div class="mt-2 pt-1">
                                        <a href="#contacts"
                                           class="btn btn-warning btn-lg"
                                           style="text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);">
                                            заказать промо в вашем городе
                                        </a>
                                    </div>
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end container-->
                </div><!-- end slide-inner -->
            </div> <!-- end swiper-slide -->

            <div class="swiper-slide container__size overflow-hidden">
                <div class="slide-inner slide-bg-image container__size right-position"
                     data-background="{% static 'images/carousel/fasade.gif' %}">
                    <div class="bg-overlay"></div>
                    <div class="container p-2">
                        <div class="row justify-content-center">
                            <div class="col-12">
                                <div class="title-heading text-start banner-title">
                                    <h2 class="title__size  text-white text-uppercase title-dark fw-bold">
                                        Медиафасады и видеоэкраны</h2>
                                    <p class="subtitle__size  ">
                                        Размещение реклама на медиафасадах и видеоэкранах вашего города
                                    </p>
                                    <a href="#contacts" class="btn btn-warning btn-lg"
                                        style="text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);">узнать подробно
                                    </a>
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end container-->
                </div><!-- end slide-inner -->
            </div> <!-- end swiper-slide -->

            <div class="swiper-slide container__size overflow-hidden">
                <div class="slide-inner slide-bg-image container__size right-position"
                     data-background="{% static 'images/carousel/banner_1_compressed.jpg' %}">
                    <div class="bg-overlay"></div>
                    <div class="container p-2">
                        <div class="row justify-content-center">
                            <div class="col-12">
                                <div class="title-heading text-start banner-title">
                                    <h2 class="title__size  text-white text-uppercase title-dark fw-bold">
                                        Промутеры и промо-модели
                                    </h2>
                                    <p class="subtitle__size ">
                                        Поиск и обучение промоутеров, подбор хостес,
                                        промо-моделей и аниматоров на мероприятия.
                                    </p>
                                    <div class="mt-2 pt-2">
                                        <a href="#contacts" class="btn btn-warning btn-lg"
                                            style="text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);">узнать подробно
                                        </a>
                                    </div>
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end container-->
                </div><!-- end slide-inner -->
            </div> <!-- end swiper-slide -->

            <div class="swiper-slide container__size overflow-hidden" >
                <div class="slide-inner slide-bg-image container__size"
                     style="background-position: center 20px right  50px no-repeat"
                     data-background="{% static 'images/carousel/banner_2_compressed.jpg' %}">
                    <div class="bg-overlay"></div>
                    <div class="container p-2">
                        <div class="row justify-content-center">
                            <div class="col-12">
                                <div class="title-heading  text-start banner-title">
                                    <h2 class="title__size  text-white text-uppercase title-dark fw-bold">
                                        Проведение event-мероприятий
                                    </h2>
                                    <p class="subtitle__size">
                                        Ивент, выставка, корпоратив, открытие магазина, торжество, вечеринка
                                    </p>
                                    <div class="mt-2 pt-2">
                                        <a href="#contacts" class="btn btn-warning btn-lg "
                                            style="text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);">организовать мероприятие
                                        </a>
                                    </div>
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end container-->
                </div><!-- end slide-inner -->
            </div> <!-- end swiper-slide -->
            <div class="swiper-slide container__size overflow-hidden">
                <div class="slide-inner slide-bg-image container__size"
                     style="background: center center;"
                     data-background="{% static 'images/carousel/banner_4_compressed.jpg' %}">
                    <div class="bg-overlay"></div>
                    <div class="container p-2">
                        <div class="row justify-content-center">
                            <div class="col-12">
                                <div class="title-heading text-start banner-title">
                                    <h2 class="title__size  text-white text-uppercase title-dark fw-bold">
                                        Раздача листовок семплинг
                                    </h2>
                                    <p class="subtitle__size ">
                                        Распространение листовок в местах с
                                        высоким трафиком и по почтовым ящикам
                                    </p>

                                    <div class="mt-2 pt-2">
                                        <a href="#contacts" class="btn btn-warning btn-lg"
                                            style="text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);">
                                            узнать о стоимости
                                        </a>
                                    </div>
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end container-->
                </div><!-- end slide-inner -->
            </div> <!-- end swiper-slide -->
            <div class="swiper-slide container__size overflow-hidden">
                <div class="slide-inner slide-bg-image container__size"
                     style="background: top center;"
                     data-background="{% static 'images/carousel/banner_6_compressed.jpg' %}">
                    <div class="bg-overlay"></div>
                    <div class="container p-2">
                        <div class="row justify-content-center">
                            <div class="col-12" >
                                <div class="title-heading text-start banner-title">
                                    <h2 class="title__size  text-white text-uppercase title-dark fw-bold">
                                        Полиграфия и брендирование
                                    </h2>
                                    <p class="subtitle__size ">
                                        Сувенирная продукция<br>нанесение логотипа на одежду,
                                        кружки или воздушные шары
                                    </p>
                                    <div class="mt-2 pt-2">
                                        <a href="#contacts" class="btn btn-warning  btn-lg"
                                            style="text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);">
                                            написать нам
                                        </a>
                                    </div>
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end container-->
                </div><!-- end slide-inner -->
            </div> <!-- end swiper-slide -->
            <div class="swiper-slide container__size overflow-hidden">
                <div class="slide-inner slide-bg-image container__size"
                     style="background: top center;"
                     data-background="{% static 'images/carousel/banner_7_compressed.jpg' %}">
                    <div class="bg-overlay"></div>
                    <div class="container p-2">
                        <div class="row justify-content-center">
                            <div class="col-12">
                                <div class="title-heading text-start banner-title">
                                    <h2 class="title__size text-white text-uppercase title-dark fw-bold">
                                        Мерчандайзинг
                                    </h2>
                                    <p class="subtitle__size   text-start  ">
                                        Визуальный мерчандайзинг и выкладка товаров<br>
                                        POS материалы и лайтбоксы
                                    </p>
                                    <div class="mt-2 pt-2">
                                        <a href="#contacts" class="btn btn-warning  btn-lg"
                                            style="text-shadow: 1px 1px 3px rgba(0, 0, 0, 1);">
                                            заказать выкладку
                                        </a>
                                    </div>
                                </div>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end container-->
                </div><!-- end slide-inner -->
            </div> <!-- end swiper-slide -->
        </div>

        <!-- end swiper-wrapper -->

        <!-- swipper controls -->
<!--         <div class="swiper-pagination swiper-pagination-bullets"></div>-->
        <div class="swiper-button-next  text-light text-center"></div>
        <div class="swiper-button-prev  text-light text-center"></div>




    </div><!--end container-->
</section><!--end section-->

core/app_site/templates/navbar.html
{% load static %}
  <nav id="navbar" class="navbar navbar-expand-lg nav-light fixed-top sticky" >
            <div class="container p-2">
                <button class="navbar-toggler p-3" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <i data-feather="menu"></i>
                </button>
                <div class="btn-group me-2" role="group" aria-label="Basic example">
                    <a type="button" class="btn btn-light mb-1 fs-5 zoom-box" href="javascript:void(0)"
                       data-bs-toggle="modal"
                       data-bs-target="#messages">
                        <i class="uil  uil-outgoing-call"></i>
                    </a>
                    <button title="скопировать телефон" id="copyPhoneBtn"
                            class="badge js-textareacopybtn  btn btn-warning mb-1 "
                            value="89008007060"
                            style="vertical-align: top;">
                        <span class="badge fs-6" style="text-shadow: 1px 1px 2px #293141">
                            +7 (909) 537 10-96</span>
                    </button>
                </div>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0" id="navbar-navlist">
                        <li class="nav-item">
                            <a class="nav-link text-warning" href="#services" aria-label="Подробно ознакомиться с услугами">услуги
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" href="#cities" aria-label="Посмотреть географию нашей работы">города
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" href="#cases" aria-label="Просмореть подробно реализованные мероприятия">кейсы
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link pe-2 text-warning" href="javascript:void(0)" data-bs-toggle="modal"
                               data-bs-target="#hh_form" aria-label="Отправить резюме">вакансии
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" href="#contacts"
                               aria-label="Напишите нам на электронную почту или в любой доступный месседжер">контакты
                            </a>

                        </li>
                    </ul>
                    <a class="navbar-brand ms-2 px-3" href="{% url 'app_site:index' %}" aria-label="Логотип BTL+">
                    <span class="logo-light-mode">
                        <img src="{% static 'images/logo/BTL_logo.svg' %}" style="text-shadow: 1px 1px 3px white" class="l-light" alt="logo btl+">
                        <img src="{% static 'images/logo/BTL_logo.svg' %}" class="l-dark" alt="logo btl+">
                    </span>

                </a>
                </div>

                <!--end collapse-->
            </div>
            <!--end container-->
        </nav>